language: php

sudo: false

notifications:
  on_success: never
  on_failure: change

php:
  - 7.0
  - 5.6

before_install:
  - pip install --user codecov
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
  - composer install --dev

before_script:
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost latest
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - export PHPCS_DIR=/tmp/phpcs
  - export SNIFFS_DIR=/tmp/sniffs
  # Install CodeSniffer for WordPress Coding Standards checks.
  - git clone -b 2.9 --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
  # Install WordPress Coding Standards.
  - git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR
  # Install PHP Compatibility sniffs.
  - git clone -b 7.1.5 --depth 1 https://github.com/wimg/PHPCompatibility.git $SNIFFS_DIR/PHPCompatibility
  # Set install path for PHPCS sniffs.
  # @link https://github.com/squizlabs/PHP_CodeSniffer/blob/4237c2fc98cc838730b76ee9cee316f99286a2a7/CodeSniffer.php#L1941
  - $PHPCS_DIR/scripts/phpcs --config-set installed_paths $SNIFFS_DIR
  # After CodeSniffer install you should refresh your path.
  - phpenv rehash
  # Install JSCS: JavaScript Code Style checker.
  # @link http://jscs.info/
  - npm install -g jscs
  # Install JSHint, a JavaScript Code Quality Tool.
  # @link http://jshint.com/docs/
  - npm install -g jshint
  # Pull in the WP Core jshint rules.
  - wget https://develop.svn.wordpress.org/trunk/.jshintrc

script:
  - mkdir -p build/logs
  # - phpunit # --coverage-clover=coverage.clover
  # Search for PHP syntax errors.
  # - find . \( -name '*kirki*.php' \) -exec php -lf {} \;
  # - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
  # Run the plugin through JSHint.
  - jshint ./controls/js/src/*.js
  - jshint ./modules/**/*.js
  # Run the plugin through JavaScript Code Style checker.
  - jscs ./controls/js/src/*.js
  # WordPress Coding Standards.
  # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
  # @link http://pear.php.net/package/PHP_CodeSniffer/
  # -p flag: Show progress of the run.
  # -s flag: Show sniff codes in all reports.
  # -v flag: Print verbose output.
  # -n flag: Do not print warnings. (shortcut for --warning-severity=0)
  # --standard: Use WordPress as the standard.
  # --extensions: Only sniff PHP files.
  - $PHPCS_DIR/scripts/phpcs -p -s -v -n ./*.php --standard=./phpcs.ruleset.xml --extensions=php
  - $PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/*.php --standard=./phpcs.ruleset.xml --extensions=php --ignore=./vendor/*.php,./tests/*.php
  - $PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/*.php --standard=./phpcs.ruleset.xml --extensions=php --ignore=./modules/webfonts/webfonts.php,./vendor/**/*.php
  - $PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/**/*.php --standard=./phpcs.ruleset.xml --extensions=php --ignore=./vendor/**/**/*.php

after_script:
  # - php vendor/bin/coveralls
  - wget https://scrutinizer-ci.com/ocular.phar
  # - php ocular.phar code-coverage:upload --format=php-clover coverage.clove

after_success:
  # - coveralls
  # - codecov
  # - bash <(curl -s https://codecov.io/bash)
